/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CallingConventions = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_32: 32,
    NUMBER_64: 64
} as const;
export type CallingConventions = typeof CallingConventions[keyof typeof CallingConventions];


export function instanceOfCallingConventions(value: any): boolean {
    for (const key in CallingConventions) {
        if (Object.prototype.hasOwnProperty.call(CallingConventions, key)) {
            if (CallingConventions[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CallingConventionsFromJSON(json: any): CallingConventions {
    return CallingConventionsFromJSONTyped(json, false);
}

export function CallingConventionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallingConventions {
    return json as CallingConventions;
}

export function CallingConventionsToJSON(value?: CallingConventions | null): any {
    return value as any;
}

