/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WaitHandle } from './WaitHandle';
import {
    WaitHandleFromJSON,
    WaitHandleFromJSONTyped,
    WaitHandleToJSON,
} from './WaitHandle';

/**
 * 
 * @export
 * @interface CancellationToken
 */
export interface CancellationToken {
    /**
     * 
     * @type {boolean}
     * @memberof CancellationToken
     */
    isCancellationRequested?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CancellationToken
     */
    canBeCanceled?: boolean;
    /**
     * 
     * @type {WaitHandle}
     * @memberof CancellationToken
     */
    waitHandle?: WaitHandle;
}

/**
 * Check if a given object implements the CancellationToken interface.
 */
export function instanceOfCancellationToken(value: object): value is CancellationToken {
    return true;
}

export function CancellationTokenFromJSON(json: any): CancellationToken {
    return CancellationTokenFromJSONTyped(json, false);
}

export function CancellationTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancellationToken {
    if (json == null) {
        return json;
    }
    return {
        
        'isCancellationRequested': json['isCancellationRequested'] == null ? undefined : json['isCancellationRequested'],
        'canBeCanceled': json['canBeCanceled'] == null ? undefined : json['canBeCanceled'],
        'waitHandle': json['waitHandle'] == null ? undefined : WaitHandleFromJSON(json['waitHandle']),
    };
}

export function CancellationTokenToJSON(value?: CancellationToken | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isCancellationRequested': value['isCancellationRequested'],
        'canBeCanceled': value['canBeCanceled'],
        'waitHandle': WaitHandleToJSON(value['waitHandle']),
    };
}

