/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CancellationToken } from './CancellationToken';
import {
    CancellationTokenFromJSON,
    CancellationTokenFromJSONTyped,
    CancellationTokenToJSON,
} from './CancellationToken';

/**
 * 
 * @export
 * @interface CancellationTokenSource
 */
export interface CancellationTokenSource {
    /**
     * 
     * @type {boolean}
     * @memberof CancellationTokenSource
     */
    isCancellationRequested?: boolean;
    /**
     * 
     * @type {CancellationToken}
     * @memberof CancellationTokenSource
     */
    token?: CancellationToken;
}

/**
 * Check if a given object implements the CancellationTokenSource interface.
 */
export function instanceOfCancellationTokenSource(value: object): value is CancellationTokenSource {
    return true;
}

export function CancellationTokenSourceFromJSON(json: any): CancellationTokenSource {
    return CancellationTokenSourceFromJSONTyped(json, false);
}

export function CancellationTokenSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancellationTokenSource {
    if (json == null) {
        return json;
    }
    return {
        
        'isCancellationRequested': json['isCancellationRequested'] == null ? undefined : json['isCancellationRequested'],
        'token': json['token'] == null ? undefined : CancellationTokenFromJSON(json['token']),
    };
}

export function CancellationTokenSourceToJSON(value?: CancellationTokenSource | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isCancellationRequested': value['isCancellationRequested'],
        'token': CancellationTokenToJSON(value['token']),
    };
}

