/* tslint:disable */
/* eslint-disable */
// @ts-nocheck 

/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CrawlStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_50: 50,
    NUMBER_51: 51,
    NUMBER_52: 52,
    NUMBER_60: 60
} as const;
export type CrawlStatus = typeof CrawlStatus[keyof typeof CrawlStatus];


export function instanceOfCrawlStatus(value: any): boolean {
    for (const key in CrawlStatus) {
        if (Object.prototype.hasOwnProperty.call(CrawlStatus, key)) {
            if (CrawlStatus[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CrawlStatusFromJSON(json: any): CrawlStatus {
    return CrawlStatusFromJSONTyped(json, false);
}

export function CrawlStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrawlStatus {
    return json as CrawlStatus;
}

export function CrawlStatusToJSON(value?: CrawlStatus | null): any {
    return value as any;
}

