/* tslint:disable */
/* eslint-disable */
// @ts-nocheck

/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CreationOrigin = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type CreationOrigin = typeof CreationOrigin[keyof typeof CreationOrigin];


export function instanceOfCreationOrigin(value: any): boolean {
    for (const key in CreationOrigin) {
        if (Object.prototype.hasOwnProperty.call(CreationOrigin, key)) {
            if (CreationOrigin[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CreationOriginFromJSON(json: any): CreationOrigin {
    return CreationOriginFromJSONTyped(json, false);
}

export function CreationOriginFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreationOrigin {
    return json as CreationOrigin;
}

export function CreationOriginToJSON(value?: CreationOrigin | null): any {
    return value as any;
}

