/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomAttributeTypedArgument
 */
export interface CustomAttributeTypedArgument {
    /**
     * 
     * @type {string}
     * @memberof CustomAttributeTypedArgument
     */
    argumentType?: string;
    /**
     * 
     * @type {any}
     * @memberof CustomAttributeTypedArgument
     */
    value?: any;
}

/**
 * Check if a given object implements the CustomAttributeTypedArgument interface.
 */
export function instanceOfCustomAttributeTypedArgument(value: object): value is CustomAttributeTypedArgument {
    return true;
}

export function CustomAttributeTypedArgumentFromJSON(json: any): CustomAttributeTypedArgument {
    return CustomAttributeTypedArgumentFromJSONTyped(json, false);
}

export function CustomAttributeTypedArgumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomAttributeTypedArgument {
    if (json == null) {
        return json;
    }
    return {
        
        'argumentType': json['argumentType'] == null ? undefined : json['argumentType'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function CustomAttributeTypedArgumentToJSON(value?: CustomAttributeTypedArgument | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'argumentType': value['argumentType'],
        'value': value['value'],
    };
}

