/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityBase
 */
export interface EntityBase {
    /**
     * 
     * @type {string}
     * @memberof EntityBase
     */
    id?: string;
}

/**
 * Check if a given object implements the EntityBase interface.
 */
export function instanceOfEntityBase(value: object): value is EntityBase {
    return true;
}

export function EntityBaseFromJSON(json: any): EntityBase {
    return EntityBaseFromJSONTyped(json, false);
}

export function EntityBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityBase {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function EntityBaseToJSON(value?: EntityBase | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

