/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EventAttributes = {
    NUMBER_0: 0,
    NUMBER_512: 512,
    NUMBER_1024: 1024,
    NUMBER_10242: 1024
} as const;
export type EventAttributes = typeof EventAttributes[keyof typeof EventAttributes];


export function instanceOfEventAttributes(value: any): boolean {
    for (const key in EventAttributes) {
        if (Object.prototype.hasOwnProperty.call(EventAttributes, key)) {
            if (EventAttributes[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EventAttributesFromJSON(json: any): EventAttributes {
    return EventAttributesFromJSONTyped(json, false);
}

export function EventAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventAttributes {
    return json as EventAttributes;
}

export function EventAttributesToJSON(value?: EventAttributes | null): any {
    return value as any;
}

