/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MethodInfo } from './MethodInfo';
import {
    instanceOfMethodInfo,
    MethodInfoFromJSON,
    MethodInfoFromJSONTyped,
    MethodInfoToJSON,
} from './MethodInfo';

/**
 * @type EventInfoAllOfRemoveMethod
 * 
 * @export
 */
export type EventInfoAllOfRemoveMethod = MethodInfo;

export function EventInfoAllOfRemoveMethodFromJSON(json: any): EventInfoAllOfRemoveMethod {
    return EventInfoAllOfRemoveMethodFromJSONTyped(json, false);
}

export function EventInfoAllOfRemoveMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventInfoAllOfRemoveMethod {
    if (json == null) {
        return json;
    }
    if (instanceOfMethodInfo(json)) {
        return MethodInfoFromJSONTyped(json, true);
    }
}

export function EventInfoAllOfRemoveMethodToJSON(value?: EventInfoAllOfRemoveMethod | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfMethodInfo(value)) {
        return MethodInfoToJSON(value as MethodInfo);
    }

    return {};
}

