/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MethodBase } from './MethodBase';
import {
    instanceOfMethodBase,
    MethodBaseFromJSON,
    MethodBaseFromJSONTyped,
    MethodBaseToJSON,
} from './MethodBase';

/**
 * @type ExceptionTargetSite
 * 
 * @export
 */
export type ExceptionTargetSite = MethodBase;

export function ExceptionTargetSiteFromJSON(json: any): ExceptionTargetSite {
    return ExceptionTargetSiteFromJSONTyped(json, false);
}

export function ExceptionTargetSiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExceptionTargetSite {
    if (json == null) {
        return json;
    }
    if (instanceOfMethodBase(json)) {
        return MethodBaseFromJSONTyped(json, true);
    }
}

export function ExceptionTargetSiteToJSON(value?: ExceptionTargetSite | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfMethodBase(value)) {
        return MethodBaseToJSON(value as MethodBase);
    }

    return {};
}

