/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtractMediaConfirmationRequest
 */
export interface ExtractMediaConfirmationRequest {
    /**
     * 
     * @type {string}
     * @memberof ExtractMediaConfirmationRequest
     */
    crawlLinkId?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtractMediaConfirmationRequest
     */
    mediaTitle?: string;
}

/**
 * Check if a given object implements the ExtractMediaConfirmationRequest interface.
 */
export function instanceOfExtractMediaConfirmationRequest(value: object): value is ExtractMediaConfirmationRequest {
    return true;
}

export function ExtractMediaConfirmationRequestFromJSON(json: any): ExtractMediaConfirmationRequest {
    return ExtractMediaConfirmationRequestFromJSONTyped(json, false);
}

export function ExtractMediaConfirmationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractMediaConfirmationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'crawlLinkId': json['crawlLinkId'] == null ? undefined : json['crawlLinkId'],
        'mediaTitle': json['mediaTitle'] == null ? undefined : json['mediaTitle'],
    };
}

export function ExtractMediaConfirmationRequestToJSON(value?: ExtractMediaConfirmationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'crawlLinkId': value['crawlLinkId'],
        'mediaTitle': value['mediaTitle'],
    };
}

