/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreationOrigin } from './CreationOrigin';
import {
    CreationOriginFromJSON,
    CreationOriginFromJSONTyped,
    CreationOriginToJSON,
} from './CreationOrigin';
import type { IProvider } from './IProvider';
import {
    IProviderFromJSON,
    IProviderFromJSONTyped,
    IProviderToJSON,
} from './IProvider';
import type { MediaCategory } from './MediaCategory';
import {
    MediaCategoryFromJSON,
    MediaCategoryFromJSONTyped,
    MediaCategoryToJSON,
} from './MediaCategory';
import type { MediaServerType } from './MediaServerType';
import {
    MediaServerTypeFromJSON,
    MediaServerTypeFromJSONTyped,
    MediaServerTypeToJSON,
} from './MediaServerType';

/**
 * 
 * @export
 * @interface ICrawlLink
 */
export interface ICrawlLink {
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    mediaId?: string;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    secondName?: string;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    formattedName?: string;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    providerId?: string;
    /**
     * 
     * @type {IProvider}
     * @memberof ICrawlLink
     */
    providerRef?: IProvider;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    providerItemId?: string;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    providerCategory?: string;
    /**
     * 
     * @type {MediaCategory}
     * @memberof ICrawlLink
     */
    category?: MediaCategory;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    fileHost?: string;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    thumbnailUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof ICrawlLink
     */
    airedEpisodesCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ICrawlLink
     */
    totalEpisodesCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ICrawlLink
     */
    season?: number;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    quality?: string;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    version?: string;
    /**
     * 
     * @type {number}
     * @memberof ICrawlLink
     */
    productionYear?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ICrawlLink
     */
    downloaded?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ICrawlLink
     */
    hasError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof ICrawlLink
     */
    authorId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ICrawlLink
     */
    isEnabled?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ICrawlLink
     */
    createdAt?: Date;
    /**
     * 
     * @type {CreationOrigin}
     * @memberof ICrawlLink
     */
    origin?: CreationOrigin;
    /**
     * 
     * @type {MediaServerType}
     * @memberof ICrawlLink
     */
    mediaServerType?: MediaServerType;
}

/**
 * Check if a given object implements the ICrawlLink interface.
 */
export function instanceOfICrawlLink(value: object): value is ICrawlLink {
    return true;
}

export function ICrawlLinkFromJSON(json: any): ICrawlLink {
    return ICrawlLinkFromJSONTyped(json, false);
}

export function ICrawlLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ICrawlLink {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'mediaId': json['mediaId'] == null ? undefined : json['mediaId'],
        'name': json['name'] == null ? undefined : json['name'],
        'secondName': json['secondName'] == null ? undefined : json['secondName'],
        'formattedName': json['formattedName'] == null ? undefined : json['formattedName'],
        'providerId': json['providerId'] == null ? undefined : json['providerId'],
        'providerRef': json['providerRef'] == null ? undefined : IProviderFromJSON(json['providerRef']),
        'providerItemId': json['providerItemId'] == null ? undefined : json['providerItemId'],
        'providerCategory': json['providerCategory'] == null ? undefined : json['providerCategory'],
        'category': json['category'] == null ? undefined : MediaCategoryFromJSON(json['category']),
        'url': json['url'] == null ? undefined : json['url'],
        'fileHost': json['fileHost'] == null ? undefined : json['fileHost'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'airedEpisodesCount': json['airedEpisodesCount'] == null ? undefined : json['airedEpisodesCount'],
        'totalEpisodesCount': json['totalEpisodesCount'] == null ? undefined : json['totalEpisodesCount'],
        'season': json['season'] == null ? undefined : json['season'],
        'quality': json['quality'] == null ? undefined : json['quality'],
        'version': json['version'] == null ? undefined : json['version'],
        'productionYear': json['productionYear'] == null ? undefined : json['productionYear'],
        'downloaded': json['downloaded'] == null ? undefined : json['downloaded'],
        'hasError': json['hasError'] == null ? undefined : json['hasError'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'isEnabled': json['isEnabled'] == null ? undefined : json['isEnabled'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'origin': json['origin'] == null ? undefined : CreationOriginFromJSON(json['origin']),
        'mediaServerType': json['mediaServerType'] == null ? undefined : MediaServerTypeFromJSON(json['mediaServerType']),
    };
}

export function ICrawlLinkToJSON(value?: ICrawlLink | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'mediaId': value['mediaId'],
        'name': value['name'],
        'secondName': value['secondName'],
        'formattedName': value['formattedName'],
        'providerId': value['providerId'],
        'providerRef': IProviderToJSON(value['providerRef']),
        'providerItemId': value['providerItemId'],
        'providerCategory': value['providerCategory'],
        'category': MediaCategoryToJSON(value['category']),
        'url': value['url'],
        'fileHost': value['fileHost'],
        'thumbnailUrl': value['thumbnailUrl'],
        'airedEpisodesCount': value['airedEpisodesCount'],
        'totalEpisodesCount': value['totalEpisodesCount'],
        'season': value['season'],
        'quality': value['quality'],
        'version': value['version'],
        'productionYear': value['productionYear'],
        'downloaded': value['downloaded'],
        'hasError': value['hasError'],
        'createdBy': value['createdBy'],
        'authorId': value['authorId'],
        'isEnabled': value['isEnabled'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'origin': CreationOriginToJSON(value['origin']),
        'mediaServerType': MediaServerTypeToJSON(value['mediaServerType']),
    };
}

