/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IDownloadLink
 */
export interface IDownloadLink {
    /**
     * 
     * @type {number}
     * @memberof IDownloadLink
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof IDownloadLink
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof IDownloadLink
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof IDownloadLink
     */
    quality?: string;
    /**
     * 
     * @type {number}
     * @memberof IDownloadLink
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof IDownloadLink
     */
    sizeUnit?: string;
}

/**
 * Check if a given object implements the IDownloadLink interface.
 */
export function instanceOfIDownloadLink(value: object): value is IDownloadLink {
    return true;
}

export function IDownloadLinkFromJSON(json: any): IDownloadLink {
    return IDownloadLinkFromJSONTyped(json, false);
}

export function IDownloadLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): IDownloadLink {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'link': json['link'] == null ? undefined : json['link'],
        'version': json['version'] == null ? undefined : json['version'],
        'quality': json['quality'] == null ? undefined : json['quality'],
        'size': json['size'] == null ? undefined : json['size'],
        'sizeUnit': json['sizeUnit'] == null ? undefined : json['sizeUnit'],
    };
}

export function IDownloadLinkToJSON(value?: IDownloadLink | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'link': value['link'],
        'version': value['version'],
        'quality': value['quality'],
        'size': value['size'],
        'sizeUnit': value['sizeUnit'],
    };
}

