/* tslint:disable */
/* eslint-disable */
// @ts-nocheck 
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { IScheduledCrawl } from './IScheduledCrawl';
import {
    instanceOfIScheduledCrawl,
    IScheduledCrawlFromJSON,
    IScheduledCrawlFromJSONTyped,
    IScheduledCrawlToJSON,
} from './IScheduledCrawl';

/**
 * @type IPlexDownloadScheduledCrawl
 * 
 * @export
 */
export type IPlexDownloadScheduledCrawl = IScheduledCrawl;

export function IPlexDownloadScheduledCrawlFromJSON(json: any): IPlexDownloadScheduledCrawl {
    return IPlexDownloadScheduledCrawlFromJSONTyped(json, false);
}

export function IPlexDownloadScheduledCrawlFromJSONTyped(json: any, ignoreDiscriminator: boolean): IPlexDownloadScheduledCrawl {
    if (json == null) {
        return json;
    }
    if (instanceOfIScheduledCrawl(json)) {
        return IScheduledCrawlFromJSONTyped(json, true);
    }
}

export function IPlexDownloadScheduledCrawlToJSON(value?: IPlexDownloadScheduledCrawl | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfIScheduledCrawl(value)) {
        return IScheduledCrawlToJSON(value as IScheduledCrawl);
    }

    return {};
}

