/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IProviderSearchItemResult
 */
export interface IProviderSearchItemResult {
    /**
     * 
     * @type {string}
     * @memberof IProviderSearchItemResult
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof IProviderSearchItemResult
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof IProviderSearchItemResult
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof IProviderSearchItemResult
     */
    thumbnailUrl?: string;
}

/**
 * Check if a given object implements the IProviderSearchItemResult interface.
 */
export function instanceOfIProviderSearchItemResult(value: object): value is IProviderSearchItemResult {
    return true;
}

export function IProviderSearchItemResultFromJSON(json: any): IProviderSearchItemResult {
    return IProviderSearchItemResultFromJSONTyped(json, false);
}

export function IProviderSearchItemResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): IProviderSearchItemResult {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'url': json['url'] == null ? undefined : json['url'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
    };
}

export function IProviderSearchItemResultToJSON(value?: IProviderSearchItemResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'url': value['url'],
        'thumbnailUrl': value['thumbnailUrl'],
    };
}

