/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IDownloadLink } from './IDownloadLink';
import {
    IDownloadLinkFromJSON,
    IDownloadLinkFromJSONTyped,
    IDownloadLinkToJSON,
} from './IDownloadLink';
import type { CrawlStatus } from './CrawlStatus';
import {
    CrawlStatusFromJSON,
    CrawlStatusFromJSONTyped,
    CrawlStatusToJSON,
} from './CrawlStatus';
import type { ICrawlLink } from './ICrawlLink';
import {
    ICrawlLinkFromJSON,
    ICrawlLinkFromJSONTyped,
    ICrawlLinkToJSON,
} from './ICrawlLink';

/**
 * 
 * @export
 * @interface IScheduledCrawl
 */
export interface IScheduledCrawl {
    /**
     * 
     * @type {string}
     * @memberof IScheduledCrawl
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof IScheduledCrawl
     */
    crawlLinkId?: string;
    /**
     * 
     * @type {string}
     * @memberof IScheduledCrawl
     */
    jobId?: string;
    /**
     * 
     * @type {ICrawlLink}
     * @memberof IScheduledCrawl
     */
    crawlLinkRef?: ICrawlLink;
    /**
     * 
     * @type {string}
     * @memberof IScheduledCrawl
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IScheduledCrawl
     */
    plexName?: string;
    /**
     * 
     * @type {string}
     * @memberof IScheduledCrawl
     */
    url?: string;
    /**
     * 
     * @type {Array<IDownloadLink>}
     * @memberof IScheduledCrawl
     */
    downloadLinks?: Array<IDownloadLink>;
    /**
     * 
     * @type {Array<IDownloadLink>}
     * @memberof IScheduledCrawl
     */
    extractedLinks?: Array<IDownloadLink>;
    /**
     * 
     * @type {CrawlStatus}
     * @memberof IScheduledCrawl
     */
    status?: CrawlStatus;
    /**
     * 
     * @type {boolean}
     * @memberof IScheduledCrawl
     */
    hasError?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof IScheduledCrawl
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the IScheduledCrawl interface.
 */
export function instanceOfIScheduledCrawl(value: object): value is IScheduledCrawl {
    return true;
}

export function IScheduledCrawlFromJSON(json: any): IScheduledCrawl {
    return IScheduledCrawlFromJSONTyped(json, false);
}

export function IScheduledCrawlFromJSONTyped(json: any, ignoreDiscriminator: boolean): IScheduledCrawl {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'crawlLinkId': json['crawlLinkId'] == null ? undefined : json['crawlLinkId'],
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
        'crawlLinkRef': json['crawlLinkRef'] == null ? undefined : ICrawlLinkFromJSON(json['crawlLinkRef']),
        'name': json['name'] == null ? undefined : json['name'],
        'plexName': json['plexName'] == null ? undefined : json['plexName'],
        'url': json['url'] == null ? undefined : json['url'],
        'downloadLinks': json['downloadLinks'] == null ? undefined : ((json['downloadLinks'] as Array<any>).map(IDownloadLinkFromJSON)),
        'extractedLinks': json['extractedLinks'] == null ? undefined : ((json['extractedLinks'] as Array<any>).map(IDownloadLinkFromJSON)),
        'status': json['status'] == null ? undefined : CrawlStatusFromJSON(json['status']),
        'hasError': json['hasError'] == null ? undefined : json['hasError'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function IScheduledCrawlToJSON(value?: IScheduledCrawl | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'crawlLinkId': value['crawlLinkId'],
        'jobId': value['jobId'],
        'crawlLinkRef': ICrawlLinkToJSON(value['crawlLinkRef']),
        'name': value['name'],
        'plexName': value['plexName'],
        'url': value['url'],
        'downloadLinks': value['downloadLinks'] == null ? undefined : ((value['downloadLinks'] as Array<any>).map(IDownloadLinkToJSON)),
        'extractedLinks': value['extractedLinks'] == null ? undefined : ((value['extractedLinks'] as Array<any>).map(IDownloadLinkToJSON)),
        'status': CrawlStatusToJSON(value['status']),
        'hasError': value['hasError'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

