/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ISearchFilterOption
 */
export interface ISearchFilterOption {
    /**
     * 
     * @type {string}
     * @memberof ISearchFilterOption
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof ISearchFilterOption
     */
    value?: string;
}

/**
 * Check if a given object implements the ISearchFilterOption interface.
 */
export function instanceOfISearchFilterOption(value: object): value is ISearchFilterOption {
    return true;
}

export function ISearchFilterOptionFromJSON(json: any): ISearchFilterOption {
    return ISearchFilterOptionFromJSONTyped(json, false);
}

export function ISearchFilterOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ISearchFilterOption {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function ISearchFilterOptionToJSON(value?: ISearchFilterOption | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'label': value['label'],
        'value': value['value'],
    };
}

