/* tslint:disable */
/* eslint-disable */
// @ts-nocheck

/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MediaCategory = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type MediaCategory = typeof MediaCategory[keyof typeof MediaCategory];


export function instanceOfMediaCategory(value: any): boolean {
    for (const key in MediaCategory) {
        if (Object.prototype.hasOwnProperty.call(MediaCategory, key)) {
            if (MediaCategory[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MediaCategoryFromJSON(json: any): MediaCategory {
    return MediaCategoryFromJSONTyped(json, false);
}

export function MediaCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaCategory {
    return json as MediaCategory;
}

export function MediaCategoryToJSON(value?: MediaCategory | null): any {
    return value as any;
}

