/* tslint:disable */
/* eslint-disable */
// @ts-nocheck

/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MediaServerType = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type MediaServerType = typeof MediaServerType[keyof typeof MediaServerType];


export function instanceOfMediaServerType(value: any): boolean {
    for (const key in MediaServerType) {
        if (Object.prototype.hasOwnProperty.call(MediaServerType, key)) {
            if (MediaServerType[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MediaServerTypeFromJSON(json: any): MediaServerType {
    return MediaServerTypeFromJSONTyped(json, false);
}

export function MediaServerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaServerType {
    return json as MediaServerType;
}

export function MediaServerTypeToJSON(value?: MediaServerType | null): any {
    return value as any;
}

