/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaCategory } from './MediaCategory';
import {
    MediaCategoryFromJSON,
    MediaCategoryFromJSONTyped,
    MediaCategoryToJSON,
} from './MediaCategory';

/**
 * 
 * @export
 * @interface MediaSearchRequest
 */
export interface MediaSearchRequest {
    /**
     * 
     * @type {string}
     * @memberof MediaSearchRequest
     */
    query?: string;
    /**
     * 
     * @type {MediaCategory}
     * @memberof MediaSearchRequest
     */
    category?: MediaCategory;
}

/**
 * Check if a given object implements the MediaSearchRequest interface.
 */
export function instanceOfMediaSearchRequest(value: object): value is MediaSearchRequest {
    return true;
}

export function MediaSearchRequestFromJSON(json: any): MediaSearchRequest {
    return MediaSearchRequestFromJSONTyped(json, false);
}

export function MediaSearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaSearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
        'category': json['category'] == null ? undefined : MediaCategoryFromJSON(json['category']),
    };
}

export function MediaSearchRequestToJSON(value?: MediaSearchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'query': value['query'],
        'category': MediaCategoryToJSON(value['category']),
    };
}

