/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MemberTypes = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_4: 4,
    NUMBER_8: 8,
    NUMBER_16: 16,
    NUMBER_32: 32,
    NUMBER_64: 64,
    NUMBER_128: 128,
    NUMBER_191: 191
} as const;
export type MemberTypes = typeof MemberTypes[keyof typeof MemberTypes];


export function instanceOfMemberTypes(value: any): boolean {
    for (const key in MemberTypes) {
        if (Object.prototype.hasOwnProperty.call(MemberTypes, key)) {
            if (MemberTypes[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MemberTypesFromJSON(json: any): MemberTypes {
    return MemberTypesFromJSONTyped(json, false);
}

export function MemberTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberTypes {
    return json as MemberTypes;
}

export function MemberTypesToJSON(value?: MemberTypes | null): any {
    return value as any;
}

