/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MethodAttributes = {
    NUMBER_0: 0,
    NUMBER_02: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_16: 16,
    NUMBER_32: 32,
    NUMBER_64: 64,
    NUMBER_128: 128,
    NUMBER_256: 256,
    NUMBER_2562: 256,
    NUMBER_512: 512,
    NUMBER_1024: 1024,
    NUMBER_2048: 2048,
    NUMBER_4096: 4096,
    NUMBER_8192: 8192,
    NUMBER_16384: 16384,
    NUMBER_32768: 32768,
    NUMBER_53248: 53248
} as const;
export type MethodAttributes = typeof MethodAttributes[keyof typeof MethodAttributes];


export function instanceOfMethodAttributes(value: any): boolean {
    for (const key in MethodAttributes) {
        if (Object.prototype.hasOwnProperty.call(MethodAttributes, key)) {
            if (MethodAttributes[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MethodAttributesFromJSON(json: any): MethodAttributes {
    return MethodAttributesFromJSONTyped(json, false);
}

export function MethodAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MethodAttributes {
    return json as MethodAttributes;
}

export function MethodAttributesToJSON(value?: MethodAttributes | null): any {
    return value as any;
}

