/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModuleHandle
 */
export interface ModuleHandle {
    /**
     * 
     * @type {number}
     * @memberof ModuleHandle
     */
    mdStreamVersion?: number;
}

/**
 * Check if a given object implements the ModuleHandle interface.
 */
export function instanceOfModuleHandle(value: object): value is ModuleHandle {
    return true;
}

export function ModuleHandleFromJSON(json: any): ModuleHandle {
    return ModuleHandleFromJSONTyped(json, false);
}

export function ModuleHandleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModuleHandle {
    if (json == null) {
        return json;
    }
    return {
        
        'mdStreamVersion': json['mdStreamVersion'] == null ? undefined : json['mdStreamVersion'],
    };
}

export function ModuleHandleToJSON(value?: ModuleHandle | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'mdStreamVersion': value['mdStreamVersion'],
    };
}

