/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrawlLink } from './CrawlLink';
import {
    CrawlLinkFromJSON,
    CrawlLinkFromJSONTyped,
    CrawlLinkToJSON,
} from './CrawlLink';

/**
 * 
 * @export
 * @interface PaginatedResponseOfCrawlLink
 */
export interface PaginatedResponseOfCrawlLink {
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseOfCrawlLink
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseOfCrawlLink
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseOfCrawlLink
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseOfCrawlLink
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<CrawlLink>}
     * @memberof PaginatedResponseOfCrawlLink
     */
    items?: Array<CrawlLink>;
}

/**
 * Check if a given object implements the PaginatedResponseOfCrawlLink interface.
 */
export function instanceOfPaginatedResponseOfCrawlLink(value: object): value is PaginatedResponseOfCrawlLink {
    return true;
}

export function PaginatedResponseOfCrawlLinkFromJSON(json: any): PaginatedResponseOfCrawlLink {
    return PaginatedResponseOfCrawlLinkFromJSONTyped(json, false);
}

export function PaginatedResponseOfCrawlLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfCrawlLink {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CrawlLinkFromJSON)),
    };
}

export function PaginatedResponseOfCrawlLinkToJSON(value?: PaginatedResponseOfCrawlLink | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CrawlLinkToJSON)),
    };
}

