/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ICrawlLink } from './ICrawlLink';
import {
    ICrawlLinkFromJSON,
    ICrawlLinkFromJSONTyped,
    ICrawlLinkToJSON,
} from './ICrawlLink';

/**
 * 
 * @export
 * @interface PaginatedResponseOfICrawlLink
 */
export interface PaginatedResponseOfICrawlLink {
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseOfICrawlLink
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseOfICrawlLink
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseOfICrawlLink
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseOfICrawlLink
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ICrawlLink>}
     * @memberof PaginatedResponseOfICrawlLink
     */
    items?: Array<ICrawlLink>;
}

/**
 * Check if a given object implements the PaginatedResponseOfICrawlLink interface.
 */
export function instanceOfPaginatedResponseOfICrawlLink(value: object): value is PaginatedResponseOfICrawlLink {
    return true;
}

export function PaginatedResponseOfICrawlLinkFromJSON(json: any): PaginatedResponseOfICrawlLink {
    return PaginatedResponseOfICrawlLinkFromJSONTyped(json, false);
}

export function PaginatedResponseOfICrawlLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfICrawlLink {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ICrawlLinkFromJSON)),
    };
}

export function PaginatedResponseOfICrawlLinkToJSON(value?: PaginatedResponseOfICrawlLink | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ICrawlLinkToJSON)),
    };
}

