/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IProviderSearchItemResult } from './IProviderSearchItemResult';
import {
    IProviderSearchItemResultFromJSON,
    IProviderSearchItemResultFromJSONTyped,
    IProviderSearchItemResultToJSON,
} from './IProviderSearchItemResult';

/**
 * 
 * @export
 * @interface PaginatedResponseOfIProviderSearchItemResult
 */
export interface PaginatedResponseOfIProviderSearchItemResult {
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseOfIProviderSearchItemResult
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseOfIProviderSearchItemResult
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseOfIProviderSearchItemResult
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponseOfIProviderSearchItemResult
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<IProviderSearchItemResult>}
     * @memberof PaginatedResponseOfIProviderSearchItemResult
     */
    items?: Array<IProviderSearchItemResult>;
}

/**
 * Check if a given object implements the PaginatedResponseOfIProviderSearchItemResult interface.
 */
export function instanceOfPaginatedResponseOfIProviderSearchItemResult(value: object): value is PaginatedResponseOfIProviderSearchItemResult {
    return true;
}

export function PaginatedResponseOfIProviderSearchItemResultFromJSON(json: any): PaginatedResponseOfIProviderSearchItemResult {
    return PaginatedResponseOfIProviderSearchItemResultFromJSONTyped(json, false);
}

export function PaginatedResponseOfIProviderSearchItemResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOfIProviderSearchItemResult {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(IProviderSearchItemResultFromJSON)),
    };
}

export function PaginatedResponseOfIProviderSearchItemResultToJSON(value?: PaginatedResponseOfIProviderSearchItemResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(IProviderSearchItemResultToJSON)),
    };
}

