/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ParameterAttributes = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_4: 4,
    NUMBER_8: 8,
    NUMBER_16: 16,
    NUMBER_4096: 4096,
    NUMBER_8192: 8192,
    NUMBER_16384: 16384,
    NUMBER_32768: 32768,
    NUMBER_61440: 61440
} as const;
export type ParameterAttributes = typeof ParameterAttributes[keyof typeof ParameterAttributes];


export function instanceOfParameterAttributes(value: any): boolean {
    for (const key in ParameterAttributes) {
        if (Object.prototype.hasOwnProperty.call(ParameterAttributes, key)) {
            if (ParameterAttributes[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ParameterAttributesFromJSON(json: any): ParameterAttributes {
    return ParameterAttributesFromJSONTyped(json, false);
}

export function ParameterAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParameterAttributes {
    return json as ParameterAttributes;
}

export function ParameterAttributesToJSON(value?: ParameterAttributes | null): any {
    return value as any;
}

