/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PropertyAttributes = {
    NUMBER_0: 0,
    NUMBER_512: 512,
    NUMBER_1024: 1024,
    NUMBER_4096: 4096,
    NUMBER_8192: 8192,
    NUMBER_16384: 16384,
    NUMBER_32768: 32768,
    NUMBER_62464: 62464
} as const;
export type PropertyAttributes = typeof PropertyAttributes[keyof typeof PropertyAttributes];


export function instanceOfPropertyAttributes(value: any): boolean {
    for (const key in PropertyAttributes) {
        if (Object.prototype.hasOwnProperty.call(PropertyAttributes, key)) {
            if (PropertyAttributes[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PropertyAttributesFromJSON(json: any): PropertyAttributes {
    return PropertyAttributesFromJSONTyped(json, false);
}

export function PropertyAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyAttributes {
    return json as PropertyAttributes;
}

export function PropertyAttributesToJSON(value?: PropertyAttributes | null): any {
    return value as any;
}

