/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Provider
 */
export interface Provider {
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Provider
     */
    enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Provider
     */
    searchEnabled?: boolean;
}

/**
 * Check if a given object implements the Provider interface.
 */
export function instanceOfProvider(value: object): value is Provider {
    return true;
}

export function ProviderFromJSON(json: any): Provider {
    return ProviderFromJSONTyped(json, false);
}

export function ProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Provider {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'] == null ? undefined : json['url'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'searchEnabled': json['searchEnabled'] == null ? undefined : json['searchEnabled'],
    };
}

export function ProviderToJSON(value?: Provider | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'displayName': value['displayName'],
        'name': value['name'],
        'url': value['url'],
        'enabled': value['enabled'],
        'searchEnabled': value['searchEnabled'],
    };
}

