/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenameCrawlLinkRequest
 */
export interface RenameCrawlLinkRequest {
    /**
     * 
     * @type {string}
     * @memberof RenameCrawlLinkRequest
     */
    newName?: string;
}

/**
 * Check if a given object implements the RenameCrawlLinkRequest interface.
 */
export function instanceOfRenameCrawlLinkRequest(value: object): value is RenameCrawlLinkRequest {
    return true;
}

export function RenameCrawlLinkRequestFromJSON(json: any): RenameCrawlLinkRequest {
    return RenameCrawlLinkRequestFromJSONTyped(json, false);
}

export function RenameCrawlLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameCrawlLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newName': json['newName'] == null ? undefined : json['newName'],
    };
}

export function RenameCrawlLinkRequestToJSON(value?: RenameCrawlLinkRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'newName': value['newName'],
    };
}

