/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IntPtr } from './IntPtr';
import {
    IntPtrFromJSON,
    IntPtrFromJSONTyped,
    IntPtrToJSON,
} from './IntPtr';

/**
 * 
 * @export
 * @interface RuntimeMethodHandle
 */
export interface RuntimeMethodHandle {
    /**
     * 
     * @type {IntPtr}
     * @memberof RuntimeMethodHandle
     */
    value?: IntPtr;
}

/**
 * Check if a given object implements the RuntimeMethodHandle interface.
 */
export function instanceOfRuntimeMethodHandle(value: object): value is RuntimeMethodHandle {
    return true;
}

export function RuntimeMethodHandleFromJSON(json: any): RuntimeMethodHandle {
    return RuntimeMethodHandleFromJSONTyped(json, false);
}

export function RuntimeMethodHandleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuntimeMethodHandle {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : IntPtrFromJSON(json['value']),
    };
}

export function RuntimeMethodHandleToJSON(value?: RuntimeMethodHandle | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'value': IntPtrToJSON(value['value']),
    };
}

