/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SafeHandle
 */
export interface SafeHandle {
    /**
     * 
     * @type {boolean}
     * @memberof SafeHandle
     */
    isClosed?: boolean;
}

/**
 * Check if a given object implements the SafeHandle interface.
 */
export function instanceOfSafeHandle(value: object): value is SafeHandle {
    return true;
}

export function SafeHandleFromJSON(json: any): SafeHandle {
    return SafeHandleFromJSONTyped(json, false);
}

export function SafeHandleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SafeHandle {
    if (json == null) {
        return json;
    }
    return {
        
        'isClosed': json['isClosed'] == null ? undefined : json['isClosed'],
    };
}

export function SafeHandleToJSON(value?: SafeHandle | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isClosed': value['isClosed'],
    };
}

