/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SafeHandleZeroOrMinusOneIsInvalid
 */
export interface SafeHandleZeroOrMinusOneIsInvalid {
    /**
     * 
     * @type {boolean}
     * @memberof SafeHandleZeroOrMinusOneIsInvalid
     */
    isClosed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SafeHandleZeroOrMinusOneIsInvalid
     */
    isInvalid?: boolean;
}

/**
 * Check if a given object implements the SafeHandleZeroOrMinusOneIsInvalid interface.
 */
export function instanceOfSafeHandleZeroOrMinusOneIsInvalid(value: object): value is SafeHandleZeroOrMinusOneIsInvalid {
    return true;
}

export function SafeHandleZeroOrMinusOneIsInvalidFromJSON(json: any): SafeHandleZeroOrMinusOneIsInvalid {
    return SafeHandleZeroOrMinusOneIsInvalidFromJSONTyped(json, false);
}

export function SafeHandleZeroOrMinusOneIsInvalidFromJSONTyped(json: any, ignoreDiscriminator: boolean): SafeHandleZeroOrMinusOneIsInvalid {
    if (json == null) {
        return json;
    }
    return {
        
        'isClosed': json['isClosed'] == null ? undefined : json['isClosed'],
        'isInvalid': json['isInvalid'] == null ? undefined : json['isInvalid'],
    };
}

export function SafeHandleZeroOrMinusOneIsInvalidToJSON(value?: SafeHandleZeroOrMinusOneIsInvalid | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isClosed': value['isClosed'],
        'isInvalid': value['isInvalid'],
    };
}

