/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SafeWaitHandle
 */
export interface SafeWaitHandle {
    /**
     * 
     * @type {boolean}
     * @memberof SafeWaitHandle
     */
    isClosed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SafeWaitHandle
     */
    isInvalid?: boolean;
}

/**
 * Check if a given object implements the SafeWaitHandle interface.
 */
export function instanceOfSafeWaitHandle(value: object): value is SafeWaitHandle {
    return true;
}

export function SafeWaitHandleFromJSON(json: any): SafeWaitHandle {
    return SafeWaitHandleFromJSONTyped(json, false);
}

export function SafeWaitHandleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SafeWaitHandle {
    if (json == null) {
        return json;
    }
    return {
        
        'isClosed': json['isClosed'] == null ? undefined : json['isClosed'],
        'isInvalid': json['isInvalid'] == null ? undefined : json['isInvalid'],
    };
}

export function SafeWaitHandleToJSON(value?: SafeWaitHandle | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isClosed': value['isClosed'],
        'isInvalid': value['isInvalid'],
    };
}

