/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduledJob
 */
export interface ScheduledJob {
    /**
     * 
     * @type {string}
     * @memberof ScheduledJob
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledJob
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledJob
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof ScheduledJob
     */
    startedAt?: Date;
}

/**
 * Check if a given object implements the ScheduledJob interface.
 */
export function instanceOfScheduledJob(value: object): value is ScheduledJob {
    return true;
}

export function ScheduledJobFromJSON(json: any): ScheduledJob {
    return ScheduledJobFromJSONTyped(json, false);
}

export function ScheduledJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledJob {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
    };
}

export function ScheduledJobToJSON(value?: ScheduledJob | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': value['type'],
        'status': value['status'],
        'startedAt': value['startedAt'] == null ? undefined : ((value['startedAt']).toISOString()),
    };
}

