/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SecurityRuleSet = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type SecurityRuleSet = typeof SecurityRuleSet[keyof typeof SecurityRuleSet];


export function instanceOfSecurityRuleSet(value: any): boolean {
    for (const key in SecurityRuleSet) {
        if (Object.prototype.hasOwnProperty.call(SecurityRuleSet, key)) {
            if (SecurityRuleSet[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SecurityRuleSetFromJSON(json: any): SecurityRuleSet {
    return SecurityRuleSetFromJSONTyped(json, false);
}

export function SecurityRuleSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityRuleSet {
    return json as SecurityRuleSet;
}

export function SecurityRuleSetToJSON(value?: SecurityRuleSet | null): any {
    return value as any;
}

