/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TriggerJobRequest
 */
export interface TriggerJobRequest {
    /**
     * 
     * @type {string}
     * @memberof TriggerJobRequest
     */
    jobType?: string;
}

/**
 * Check if a given object implements the TriggerJobRequest interface.
 */
export function instanceOfTriggerJobRequest(value: object): value is TriggerJobRequest {
    return true;
}

export function TriggerJobRequestFromJSON(json: any): TriggerJobRequest {
    return TriggerJobRequestFromJSONTyped(json, false);
}

export function TriggerJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'jobType': json['jobType'] == null ? undefined : json['jobType'],
    };
}

export function TriggerJobRequestToJSON(value?: TriggerJobRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jobType': value['jobType'],
    };
}

