/* tslint:disable */
/* eslint-disable */
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SafeWaitHandle } from './SafeWaitHandle';
import {
    SafeWaitHandleFromJSON,
    SafeWaitHandleFromJSONTyped,
    SafeWaitHandleToJSON,
} from './SafeWaitHandle';
import type { WaitHandleAllOfHandle } from './WaitHandleAllOfHandle';
import {
    WaitHandleAllOfHandleFromJSON,
    WaitHandleAllOfHandleFromJSONTyped,
    WaitHandleAllOfHandleToJSON,
} from './WaitHandleAllOfHandle';

/**
 * 
 * @export
 * @interface WaitHandle
 */
export interface WaitHandle {
    /**
     * 
     * @type {WaitHandleAllOfHandle}
     * @memberof WaitHandle
     * @deprecated
     */
    handle?: WaitHandleAllOfHandle;
    /**
     * 
     * @type {SafeWaitHandle}
     * @memberof WaitHandle
     */
    safeWaitHandle?: SafeWaitHandle;
}

/**
 * Check if a given object implements the WaitHandle interface.
 */
export function instanceOfWaitHandle(value: object): value is WaitHandle {
    return true;
}

export function WaitHandleFromJSON(json: any): WaitHandle {
    return WaitHandleFromJSONTyped(json, false);
}

export function WaitHandleFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitHandle {
    if (json == null) {
        return json;
    }
    return {
        
        'handle': json['handle'] == null ? undefined : WaitHandleAllOfHandleFromJSON(json['handle']),
        'safeWaitHandle': json['safeWaitHandle'] == null ? undefined : SafeWaitHandleFromJSON(json['safeWaitHandle']),
    };
}

export function WaitHandleToJSON(value?: WaitHandle | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'handle': WaitHandleAllOfHandleToJSON(value['handle']),
        'safeWaitHandle': SafeWaitHandleToJSON(value['safeWaitHandle']),
    };
}

