/* tslint:disable */
/* eslint-disable */
// @ts-nocheck 
/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type WaitHandleAllOfHandle
 * 
 * @export
 */
export type WaitHandleAllOfHandle = object;

export function WaitHandleAllOfHandleFromJSON(json: any): WaitHandleAllOfHandle {
    return WaitHandleAllOfHandleFromJSONTyped(json, false);
}

export function WaitHandleAllOfHandleFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitHandleAllOfHandle {
    if (json == null) {
        return json;
    }
    if (instanceOfobject(json)) {
        return objectFromJSONTyped(json, true);
    }
}

export function WaitHandleAllOfHandleToJSON(value?: WaitHandleAllOfHandle | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfobject(value)) {
        return objectToJSON(value as object);
    }

    return {};
}

