/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CancellationToken } from '../models/CancellationToken';
import { HttpFile } from '../http/http';

export class CancellationTokenSource {
    'isCancellationRequested'?: boolean;
    'token'?: CancellationToken;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isCancellationRequested",
            "baseName": "isCancellationRequested",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "CancellationToken",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CancellationTokenSource.attributeTypeMap;
    }

    public constructor() {
    }
}

