/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WaitHandle } from '../models/WaitHandle';
import { HttpFile } from '../http/http';

export class CancellationToken {
    'isCancellationRequested'?: boolean;
    'canBeCanceled'?: boolean;
    'waitHandle'?: WaitHandle;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isCancellationRequested",
            "baseName": "isCancellationRequested",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canBeCanceled",
            "baseName": "canBeCanceled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "waitHandle",
            "baseName": "waitHandle",
            "type": "WaitHandle",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CancellationToken.attributeTypeMap;
    }

    public constructor() {
    }
}

