/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EntityBase {
    'id'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "guid"
        }    ];

    static getAttributeTypeMap() {
        return EntityBase.attributeTypeMap;
    }

    public constructor() {
    }
}

