/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreationOrigin } from '../models/CreationOrigin';
import { IProvider } from '../models/IProvider';
import { MediaCategory } from '../models/MediaCategory';
import { MediaServerType } from '../models/MediaServerType';
import { HttpFile } from '../http/http';

export class ICrawlLink {
    'id'?: string;
    'mediaId'?: string;
    'name'?: string;
    'secondName'?: string;
    'formattedName'?: string;
    'providerId'?: string;
    'providerRef'?: IProvider;
    'providerItemId'?: string | null;
    'providerCategory'?: string | null;
    'category'?: MediaCategory;
    'url'?: string;
    'fileHost'?: string;
    'thumbnailUrl'?: string | null;
    'airedEpisodesCount'?: number | null;
    'totalEpisodesCount'?: number | null;
    'season'?: number | null;
    'quality'?: string | null;
    'version'?: string;
    'productionYear'?: number | null;
    'downloaded'?: boolean;
    'hasError'?: boolean;
    'createdBy'?: string | null;
    'authorId'?: string;
    'createdAt'?: Date;
    'origin'?: CreationOrigin;
    'mediaServerType'?: MediaServerType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "guid"
        },
        {
            "name": "mediaId",
            "baseName": "mediaId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "secondName",
            "baseName": "secondName",
            "type": "string",
            "format": ""
        },
        {
            "name": "formattedName",
            "baseName": "formattedName",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerId",
            "baseName": "providerId",
            "type": "string",
            "format": "guid"
        },
        {
            "name": "providerRef",
            "baseName": "providerRef",
            "type": "IProvider",
            "format": ""
        },
        {
            "name": "providerItemId",
            "baseName": "providerItemId",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerCategory",
            "baseName": "providerCategory",
            "type": "string",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "MediaCategory",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileHost",
            "baseName": "fileHost",
            "type": "string",
            "format": ""
        },
        {
            "name": "thumbnailUrl",
            "baseName": "thumbnailUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "airedEpisodesCount",
            "baseName": "airedEpisodesCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "totalEpisodesCount",
            "baseName": "totalEpisodesCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "season",
            "baseName": "season",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "quality",
            "baseName": "quality",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "productionYear",
            "baseName": "productionYear",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "downloaded",
            "baseName": "downloaded",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasError",
            "baseName": "hasError",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorId",
            "baseName": "authorId",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "origin",
            "baseName": "origin",
            "type": "CreationOrigin",
            "format": ""
        },
        {
            "name": "mediaServerType",
            "baseName": "mediaServerType",
            "type": "MediaServerType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ICrawlLink.attributeTypeMap;
    }

    public constructor() {
    }
}



