/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class IDownloadLink {
    'index'?: number;
    'link'?: string;
    'version'?: string;
    'quality'?: string;
    'size'?: number;
    'sizeUnit'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "quality",
            "baseName": "quality",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number",
            "format": "float"
        },
        {
            "name": "sizeUnit",
            "baseName": "sizeUnit",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IDownloadLink.attributeTypeMap;
    }

    public constructor() {
    }
}

