/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CancellationTokenSource } from '../models/CancellationTokenSource';
import { IPlexDownloadScheduledCrawl } from '../models/IPlexDownloadScheduledCrawl';
import { HttpFile } from '../http/http';

export class IPlexDownload {
    'name'?: string;
    'fileName'?: string;
    'url'?: string;
    'destinationFolder'?: string;
    'scheduledCrawl'?: IPlexDownloadScheduledCrawl | null;
    'isRunning'?: boolean;
    'isCancelled'?: boolean;
    'isCompleted'?: boolean;
    'isDeadLink'?: boolean;
    'episodeIndex'?: number;
    'progress'?: number;
    'speed'?: number;
    'speedUnit'?: string;
    'averageSpeed'?: number;
    'averageSpeedUnit'?: string;
    'sizeReceived'?: number;
    'sizeUnit'?: string;
    'totalSize'?: number;
    'totalSizeUnit'?: string;
    'estimatedTime'?: number;
    'estimatedTimeUnit'?: string;
    'cancellationTokenSource'?: CancellationTokenSource;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileName",
            "baseName": "fileName",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationFolder",
            "baseName": "destinationFolder",
            "type": "string",
            "format": ""
        },
        {
            "name": "scheduledCrawl",
            "baseName": "scheduledCrawl",
            "type": "IPlexDownloadScheduledCrawl",
            "format": ""
        },
        {
            "name": "isRunning",
            "baseName": "isRunning",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isCancelled",
            "baseName": "isCancelled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isCompleted",
            "baseName": "isCompleted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isDeadLink",
            "baseName": "isDeadLink",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "episodeIndex",
            "baseName": "episodeIndex",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "progress",
            "baseName": "progress",
            "type": "number",
            "format": "double"
        },
        {
            "name": "speed",
            "baseName": "speed",
            "type": "number",
            "format": "double"
        },
        {
            "name": "speedUnit",
            "baseName": "speedUnit",
            "type": "string",
            "format": ""
        },
        {
            "name": "averageSpeed",
            "baseName": "averageSpeed",
            "type": "number",
            "format": "double"
        },
        {
            "name": "averageSpeedUnit",
            "baseName": "averageSpeedUnit",
            "type": "string",
            "format": ""
        },
        {
            "name": "sizeReceived",
            "baseName": "sizeReceived",
            "type": "number",
            "format": "double"
        },
        {
            "name": "sizeUnit",
            "baseName": "sizeUnit",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalSize",
            "baseName": "totalSize",
            "type": "number",
            "format": "double"
        },
        {
            "name": "totalSizeUnit",
            "baseName": "totalSizeUnit",
            "type": "string",
            "format": ""
        },
        {
            "name": "estimatedTime",
            "baseName": "estimatedTime",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "estimatedTimeUnit",
            "baseName": "estimatedTimeUnit",
            "type": "string",
            "format": ""
        },
        {
            "name": "cancellationTokenSource",
            "baseName": "cancellationTokenSource",
            "type": "CancellationTokenSource",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IPlexDownload.attributeTypeMap;
    }

    public constructor() {
    }
}

