/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ICrawlLink } from '../models/ICrawlLink';
import { HttpFile } from '../http/http';

export class IProvider {
    'id'?: string;
    'displayName'?: string;
    'name'?: string;
    'url'?: string;
    'enabled'?: boolean;
    'searchEnabled'?: boolean;
    'crawlLinksRef'?: Array<ICrawlLink>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "guid"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "searchEnabled",
            "baseName": "searchEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "crawlLinksRef",
            "baseName": "crawlLinksRef",
            "type": "Array<ICrawlLink>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IProvider.attributeTypeMap;
    }

    public constructor() {
    }
}

