/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CrawlStatus } from '../models/CrawlStatus';
import { ICrawlLink } from '../models/ICrawlLink';
import { IDownloadLink } from '../models/IDownloadLink';
import { HttpFile } from '../http/http';

export class IScheduledCrawl {
    'id'?: string;
    'crawlLinkId'?: string;
    'jobId'?: string;
    'crawlLinkRef'?: ICrawlLink;
    'name'?: string;
    'plexName'?: string | null;
    'url'?: string;
    'downloadLinks'?: Array<IDownloadLink>;
    'extractedLinks'?: Array<IDownloadLink>;
    'status'?: CrawlStatus;
    'hasError'?: boolean;
    'createdAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "guid"
        },
        {
            "name": "crawlLinkId",
            "baseName": "crawlLinkId",
            "type": "string",
            "format": "guid"
        },
        {
            "name": "jobId",
            "baseName": "jobId",
            "type": "string",
            "format": ""
        },
        {
            "name": "crawlLinkRef",
            "baseName": "crawlLinkRef",
            "type": "ICrawlLink",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "plexName",
            "baseName": "plexName",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "downloadLinks",
            "baseName": "downloadLinks",
            "type": "Array<IDownloadLink>",
            "format": ""
        },
        {
            "name": "extractedLinks",
            "baseName": "extractedLinks",
            "type": "Array<IDownloadLink>",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CrawlStatus",
            "format": ""
        },
        {
            "name": "hasError",
            "baseName": "hasError",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return IScheduledCrawl.attributeTypeMap;
    }

    public constructor() {
    }
}



