/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MediaCategory } from '../models/MediaCategory';
import { HttpFile } from '../http/http';

export class MediaSearchRequest {
    'query'?: string;
    'category'?: MediaCategory;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "query",
            "baseName": "query",
            "type": "string",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "MediaCategory",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MediaSearchRequest.attributeTypeMap;
    }

    public constructor() {
    }
}



