/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ICrawlLink } from '../models/ICrawlLink';
import { HttpFile } from '../http/http';

export class PaginatedResponseOfICrawlLink {
    'currentPage'?: number;
    'totalPages'?: number;
    'pageSize'?: number;
    'totalCount'?: number;
    'items'?: Array<ICrawlLink>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currentPage",
            "baseName": "currentPage",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "totalPages",
            "baseName": "totalPages",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ICrawlLink>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaginatedResponseOfICrawlLink.attributeTypeMap;
    }

    public constructor() {
    }
}

