/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TriggerJobRequest {
    'jobType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobType",
            "baseName": "jobType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TriggerJobRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

