/**
 * PlexBot API
 * This the PlexBot Web API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: filip.iricanin@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SafeWaitHandle } from '../models/SafeWaitHandle';
import { WaitHandleAllOfHandle } from '../models/WaitHandleAllOfHandle';
import { HttpFile } from '../http/http';

export class WaitHandle {
    'handle'?: WaitHandleAllOfHandle;
    'safeWaitHandle'?: SafeWaitHandle;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "handle",
            "baseName": "handle",
            "type": "WaitHandleAllOfHandle",
            "format": ""
        },
        {
            "name": "safeWaitHandle",
            "baseName": "safeWaitHandle",
            "type": "SafeWaitHandle",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WaitHandle.attributeTypeMap;
    }

    public constructor() {
    }
}

